name: Publish to NPM

on:
  push:
    branches:
      - release
      - release-*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - name: Setup .npmrc (NPM)
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Get Current version
        id: current_version
        run: echo version=$(node -p "require('./package.json').version") >> $GITHUB_OUTPUT

      - name: Get current npm version
        id: npm_version
        run: echo version=$(npm view arunabase version) >> $GITHUB_OUTPUT

      - name: Compare versions and skip if same
        id: compare_versions
        if: ${{ steps.current_version.outputs.version == steps.npm_version.outputs.version }}
        run: echo "skip=true" >> $GITHUB_OUTPUT && echo "Skipping publish because versions are the same" && exit 0

      - name: Publish to npm (alpha)
        if: ${{ contains(steps.current_version.outputs.version, '-alpha') && steps.compare_versions.outputs.skip != 'true' }}
        run: npm publish --provenance --access=public --tag alpha

      - name: Publish to npm (beta)
        if: ${{ contains(steps.current_version.outputs.version, '-beta') && steps.compare_versions.outputs.skip != 'true' }}
        run: npm publish --provenance --access=public --tag beta

      - name: Publish to npm (latest)
        if: ${{ !contains(steps.current_version.outputs.version, '-alpha') && !contains(steps.current_version.outputs.version, '-beta') && steps.compare_versions.outputs.skip != 'true' }}
        run: npm publish --provenance --access=public
